name: Release (Github Package Registry)

on:
  pull_request:
    types:
      - closed
    branches:
      - 'master'
    paths-ignore:
      - '.github/dependabot.yml'

env:
  IMAGE: ghcr.io/${{ github.repository }}/simple-slack-poster:${{ github.sha }}

jobs:
  release:
    if: github.event.pull_request.merged == true
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        name: Checkout
      - id: bump
        uses: zwaldowski/match-label-action@main
        with:
          allowed: major,minor,patch
      - id: next_version
        uses: zwaldowski/semver-release-action@main
        name: Prepare and tag release with semver
        with:
          bump: ${{ steps.bump.outputs.match }}
          prefix: v
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ncipollo/release-action@main
        name: Create release
        with:
          tag: ${{ steps.next_version.outputs.version_tag }}
          generateReleaseNotes: true
